## Introduction to OOP in Python
 One of the popular approach to solve a programming problem by creating objects.<br>
 This is known as Object Oriented Programming.<br>
 An object has two characteristics:<br>
 1.attributes(name,age,color)<br>
 2.behaviour(learn,study,etc)<br>

 In Python, the concept OOP follow these things:<br>
 1.Inheritence<br>
 2.Encapsulation<br>
 3.Polymorphism<br>

 class: A class is blueprint for the object.<br>
 Object: Blueprint of class or Instance of the class or Physical entity.<br>
 Methods: Part of class and can be called with object.<br>
 Constructors: Part of class and can be called automatically when the class object is created.<br>
 ### class className:¶
 some functions and variables<br>
 function--used to write function to perform a specific task<br>
 variables--data(memory)<br>

In [4]:
def test():
    print("test() for function")
    return
test()

test() for function


In [5]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo() # Object creation
obj.test() # call for the method

test() for the class and method


In [6]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
        return
p1=Demo1()
p1.fact(5)

120

In [8]:
# method
# def test(self,parameter1,parameter2)
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [9]:
class Person():
    #constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#Derived class
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())
emp1=Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


### Python Numpy
          Numpy arrays is a bit like python list.
          Numpy array is a central data structure of the numpy lib.
          This lib actually short for 'Numeric Python' or 'Numerical Python'.

In [10]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print (array)


[1 2 3 4]


In [11]:
import numpy as np
lst=[1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [12]:
lst=[1.0,2.5,6.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(3,)
float64


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [14]:
# Re-shape the given array
# numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# Append some data-- horizontally
# hstack(array1,array2)-- will be automatically arranged horizontally.
# Append some data-- vertically
# vstack(array1,array2)-- will be automatically arranged vertically.
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [16]:
# Generate random number from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.29594807 4.68280844 4.97750472 5.34696368 5.40896659 5.24781494
 4.84882682 4.59672361 4.57185305 5.41475102]


In [17]:
# numpy.zeros() and numpy.one()
# Generate an array with all zeros-- numpy.zeros()
# numpy.zeros(shape,dtype=float-,order='C')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [19]:
# np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [20]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [21]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [22]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [23]:
# arrange()-- particular
# numpy.arrange(start,end,step)
# start-value
# end  -value
# step- gap between one value to another value
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [25]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [26]:
# indexing and slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [27]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

first row [1 2 3]


In [28]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row",a1[1])

second row [4 5 6]


In [29]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row",a1[:1])

slicing row [[1 2 3]]


In [30]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column",a1[:,1])

slicing column [2 5]


In [31]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column",a1[:,2])

slicing last column [3 6]


In [32]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column",a1[1:,1])

row and column [5]


In [33]:
# some math operations on given random numbers
# min  -- returns the least number
# max  -- returns the large number
# mean -- mean
# median--median
# GD  -- Gaussian distribution
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[4.95973545 3.70309715 6.16894662 4.77905529 6.29622253 3.24687974
 5.44870618 5.20236109 4.99649765 5.42570948]
min value= 3.2468797392453705
max value= 6.2962225302225185
mean value= 5.0227211187076275
median value= 5.099429369450909


In [34]:
# Multiplication of 1D arrays
# numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [35]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [36]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

### Pandas basics
           Python is one of the popular programming language for data analysis.
           Python is offering the lib called Pandas used for importing and analyzing pretty much faster and easier also.
### Pandas DataFrames Data Analysis with Python

In [39]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"Mobile number":[999,777,888,333,222,666],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  Mobile number Address
0    Anil    anil@gmail.com            999     Hyd
1   Akhil   akhil@gmail.com            777     Hyd
2  Dinesh  dinesh@gmail.com            888     Hyd
3  Harsha  harsha@gmail.com            333     Hyd
4    Ajay    ajay@gmail.com            222     Hyd
5  Kranth  kranth@gmail.com            666     Hyd


In [40]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  Mobile number Address
01    Anil    anil@gmail.com            999     Hyd
02   Akhil   akhil@gmail.com            777     Hyd
03  Dinesh  dinesh@gmail.com            888     Hyd
04  Harsha  harsha@gmail.com            333     Hyd
05    Ajay    ajay@gmail.com            222     Hyd
06  Kranth  kranth@gmail.com            666     Hyd


In [42]:
import calendar
c1=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [43]:
def frequency(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if(ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequency(a)

0 4 1 1 1 1 1 0 0 0 

In [44]:
def check(s1, s2): 
      
    # the sorted strings are checked  
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2)

The strings are anagrams.


## Day 12

In [45]:
#create a series of numbers by passing a list of values 
import pandas as pd
a=pd.Series([1,3,4,5,6,7])
print(a)

0    1
1    3
2    4
3    5
4    6
5    7
dtype: int64


In [46]:
import numpy as np
a1=pd.Series([1,2,3,4,np.nan,6])
print(a1)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
dtype: float64


In [50]:
dates=pd.date_range('20190601',periods=20)
print(dates)

DatetimeIndex(['2019-06-01', '2019-06-02', '2019-06-03', '2019-06-04',
               '2019-06-05', '2019-06-06', '2019-06-07', '2019-06-08',
               '2019-06-09', '2019-06-10', '2019-06-11', '2019-06-12',
               '2019-06-13', '2019-06-14', '2019-06-15', '2019-06-16',
               '2019-06-17', '2019-06-18', '2019-06-19', '2019-06-20'],
              dtype='datetime64[ns]', freq='D')


In [51]:
lst=pd.date_range('20190601',periods=20)
print(lst)

DatetimeIndex(['2019-06-01', '2019-06-02', '2019-06-03', '2019-06-04',
               '2019-06-05', '2019-06-06', '2019-06-07', '2019-06-08',
               '2019-06-09', '2019-06-10', '2019-06-11', '2019-06-12',
               '2019-06-13', '2019-06-14', '2019-06-15', '2019-06-16',
               '2019-06-17', '2019-06-18', '2019-06-19', '2019-06-20'],
              dtype='datetime64[ns]', freq='D')


In [62]:
a3=pd.DataFrame({'A':1,
                'B':pd.Timestamp('20190601'),
                'C':pd.Series(1,index=list(range(4),dtype='float32'),
                'D':np.array([3]*4,dtype='int32'),
                'E':pd.Categorical(["test","train","test","train"]),
                'F':"foo"})
print(a3)
                 

SyntaxError: invalid syntax (<ipython-input-62-cfbb79df71b6>, line 4)

In [63]:
#Turtle is a python feature like a drawing board
#lines, square star, rectand etc
#Turtle()-- It creates and returns a new turtle object

In [64]:
#step1- make all 'turtle' package to be imported
import turtle as tt
#Turtle method creates and returns the new object
a1=tt.Turtle()
#forward method moves 100 pixels
tt.forward(100)
#we are done
tt.done()

In [69]:
#Drawing a square
import turtle as tt
a1=tt.Turtle()
a1.forward(150)
a1.right(90)

a1.forward(150)
a1.right(90)

a1.forward(150)
a1.right(90)

a1.forward(150)
a1.right(90)

tt.done()

In [74]:
#Drawing a star
import turtle as tt
a1=tt.Turtle()

for x in range(40):
    a1.forward(50)
    a1.right(144)

tt.done()

In [ ]:
import turtle as tt
a1=tt.Turtle()

for i in range(40):
    a1.forward(i*10)
    a1.right(144)

tt.done()

In [ ]:
import turtle as tt

c1=tt.Turtle()
c1.pencolor("blue")
for i in range(50):
    c1.forward(50)
    c1.left(123)

c1.pencolor("red")
for i in range(50):
    c1.forward(100)
    c1.left(123)    
    
tt.done()

In [ ]:
import turtle as tt

colors=['red','blue','orange','yellow','purple']

a1=tt.Turtle()

for x in range(360):
    a1.pencolor(colors[x%6])
    a1.width(x/100+1)
    a1.forward(x)
    a1.left(59)
    
tt.done()

In [ ]:
import turtle as tt
a1=tt.Turtle()

colors=['red','blue','orange','yellow','purple']
dot_distance=10
width=10
height=15

a1.penup()

for x in range(height):
    a1.pencolor(colors[x%6])
    for i in range(width):
        a1.dot()
        a1.forward(dot_distance)
    a1.forward(dot_distance*width)
    a1.right(90)
    a1.forward(dot_distance)
    a1.left(90)
    
tt.done()    

In [ ]:
from turtle import
import random
for n in range(50):
    penup()
    goto(random.randint(-400,400),random.rantint(-400,400))
    pendown()
    
    red_amount= random.randint(0,30)/100.0
    blue_amount =random.randint(50,100)/100.0
    green_amount=random.randint(0,30)/100.0
    
    pencolor((red_amount,blue_amount,green_amount))
    
    circle_size=random.randint(10,40)
    pensize(random.randint(4,6))
    
    for i in range(6):
        circle(cirle_size)
        left(60)
        
tt.done()      

In [ ]:
from turtle import*
import random

def main():
    colors=("red","orange",)